### ISSUE TITLE
No navigation bar 

### ISSUE THREAD

**Issue by fabianbr80** [bhavin008/bj_polaroyd#1]
After importing the Polaroyd template into Typo3 8.7, the navigation bar of the menu at the top is not visible. Only "Menu" is displayed

**Comment by bhavin008** [comment]
Might be you need to set the Root ID if you have multidomain in your installation.
Backend:
1) https://i.imgur.com/ecOmhAi.png
2) Set the page ID here: https://i.imgur.com/gaGrFja.png
